notes: |
  Uses SVGs symbols which are stored in `layouts/includes`. Has variables for icon, fill color and size.
context:
  icon:
    - application
    - arrow-down
    - arrow-right
    - assistance
    - asterisk
    - bed
    - browse
    - building
    - calendar
    - check
    - clock
    - close
    - close-round
    - cross
    - down
    - download
    - edit
    - eligibility
    - equalizer
    - eye
    - favorite
    - file
    - filter-qty--0
    - filter-qty--1
    - filter-qty--2
    - filter-qty--3
    - filter-qty--4
    - filter-qty--5
    - filter-qty--6
    - filter-qty--7
    - filter-qty--8
    - filter-qty--9
    - forward
    - globe
    - info
    - left
    - light-bulb
    - like
    - like-fill
    - link
    - list
    - list-unordered
    - lock
    - oval
    - mail
    - map
    - map-thin
    - menu
    - minus
    - phone
    - plus
    - polygon
    - profile
    - question
    - result
    - right
    - search
    - settings
    - star
    - ticket
    - trash
    - warning
  fill:
    -  primary
    -  success
  size:
    - small
    - medium
    - large
