notes: |
  Uses SVGs symbols which are stored in `layouts/includes`. Has variables for icon, fill color and size.
context:
  icon:
    - arrow-down
    - download
    - forward
    - info
    - like
    - mail
    - map
    - menu
    - plus
    - search
    - warning
    - check
    - close
    - globe
    - question
    - link
    - phone
    - right
    - left
    - asterisk
    - edit
    - lock
    - ticket
    - list
    - light bulb
    - clock
    - eye
    - file
    - bed
    - calendar
    - building
    - result
    - minus
  fill:
    -  primary
    -  success
  size:
    - small
    - medium
    - large
