context:
   menus:
      account:
        - name: My Dashboard
          icon: profile
        - name: My Applications
          icon: application
        - name: My Favorites
          icon: favorite
        - name: Eligibility Settings
          icon: eligibility
        - name: Account Settings
          icon: settings
        - name: Sign Out
      mobile:
        - name: Browse Properties
          icon: browse
        - name: Get Assistance
          icon: assistance
        - name: My Favorites
          icon: favorite
        - name: Eligibility Settings
          icon: eligibility
        - name: Account Settings
          icon: settings
        - name: Sign Out
      lang:
        - name: English
          active: true
          url: application-expect.html
          selected: true
          index: 0
          id: panel1
        - name: Español
          url: application-expect--es.html
          selected: false
          index: -1
          id: panel2
        - name: '中文'
          chinese: true
          url: application-expect--zh.html
          selected: false
          index: -1
          id: panel3
        - name: Filipino
          url: "#"
          selected: false
          index: -1
          id: panel4
