preview: "@angular"
label: My Application
context:
  page-class: center-body
  sections:
    - header: You
      info-items:
        - name: Name
          value: Laura Smith
        - name: Date of Birth
          value: 12/02/1980
        - name: Phone
          value: 415-123-1234
          note: Cell
        - name: Additional Phone
          value: 415-123-1234
          note: Home
        - name: Email
          value: lara.smith@gmail.com
        - name: Address
          value: 649 Avalon St <br> San Francisco, CA 94117
        - name: Mailing Address
          value: 456 Mission St <br> San Francisco, CA 94117
    - header: Alternate Contact
      info-items:
        - name: Name
          value: Michael Smith
          note: Counselor
          secondary: MEDA
        - name: Email
          value: michael.smith@gmail.com
        - name: Phone
          value: 415-876-5432
        - name: Mailing Address
          value: 456 Mission St <br> San Francisco, CA 94117
    - header: Household Members
      info-items:
        - name: Name
          value: Michael Smith
          note: Child
        - name: Date of Birth
          value: 12/2/1980
        - divider: true
        - name: Name
          value: Michael Johnson
          note: Family Member
        - name: Date of Birth
          value: 12/2/1970
        - name: Address
          value: 700 Avalon St <br> San Francisco, CA 94117
    - header: Household Details
      info-items:
        - name: Rent at 2106 Park Blvd
          value: $1200 per month
          note: for Michael Smith
        - name: Rent at 4106 Terrace St
          value: $1200 per month
          note: for Jane Smith and Denise Jones
        - name: Seniors in Household
          value: Yes
        - name: Veterans in Household
          value: Yes
        - name: People with Developmental Disabilities
          value: Yes
        - name: ADA Accessible Units
          value: Mobility Impairments<br> Visual Impairments
    - header: Income
      info-items:
        - name: Vouchers and Subsidies
          value: Yes
        - name: Household Income
          value: $32,000 per year
    - header: Preferences
      info-items:
        - name: You Have Claimed
          value: Certificate of Preference
          note: for Michael Smith
        - name: You Have Claimed
          value: Neighborhood Resident Housing Preference
          note: for Michael Smith 
          secondary: Telephone Bill attached
        - name: You Have Claimed
          value: Rent Burden Preference
          note: for 2106 Park Blvd
          secondary: Copy of Lease and Cancelled Check attached
          note-2: for 4106 Terrace St
          secondary-2: Copy of Lease and Money order attached

  sections-general:
    - header: You
      info-items:
        - name: Name
          value: Laura Smith
        - name: Date of Birth
          value: 12/02/1980
        - name: Phone
          value: 415-123-1234
          note: Cell
        - name: Additional Phone
          value: 415-123-1234
          note: Home
        - name: Email
          value: lara.smith@gmail.com
        - name: Address
          value: 649 Avalon St <br> San Francisco, CA 94117
        - name: Mailing Address
          value: 456 Mission St <br> San Francisco, CA 94117
    - header: Alternate Contact
      info-items:
        - name: Name
          value: Michael Smith
          note: Counselor
          secondary: MEDA
        - name: Email
          value: michael.smith@gmail.com
        - name: Phone
          value: 415-876-5432
        - name: Mailing Address
          value: 456 Mission St <br> San Francisco, CA 94117
    - header: Household Members
      info-items:
        - name: Name
          value: Michael Smith
          note: Child
        - name: Date of Birth
          value: 12/2/1980
        - divider: true
        - name: Name
          value: Michael Johnson
          note: Family Member
        - name: Date of Birth
          value: 12/2/1970
        - name: Address
          value: 700 Avalon St <br> San Francisco, CA 94117
    - header: Preferences
      info-items:
        - name: 
          value: Based on the information you have entered, your household has not claimed any housing lottery preferences. you will be in the general lottery.
          is-sentence: yes
    - header: Income
      info-items:
        - name: Vouchers and Subsidies
          value: "No"
        - name: Household Income
          value: $32,000 per year

  sections-preview:
    - header: You
      info-items:
        - name: Name
          value: Laura Smith
        - name: Date of Birth
          value: 12/02/1980
        - name: Phone
          value: 415-123-1234
          note: Cell
        - name: Additional Phone
          value: 415-123-1234
          note: Home
        - name: Email
          value: lara.smith@gmail.com
        - name: Address
          value: 649 Avalon St <br> San Francisco, CA 94117
        - name: Mailing Address
          value: 456 Mission St <br> San Francisco, CA 94117
    - header: Alternate Contact
      info-items:
        - name: Name
          value: Michael Smith
          note: Counselor
          secondary: MEDA
        - name: Email
          value: michael.smith@gmail.com
        - name: Phone
          value: 415-876-5432
        - name: Mailing Address
          value: 456 Mission St <br> San Francisco, CA 94117
    - header: Household Members
      info-items:
        - name: Name
          value: Michael Smith
          note: Child
        - name: Date of Birth
          value: 12/2/1980
        - divider: true
        - name: Name
          value: Michael Johnson
          note: Family Member
        - name: Date of Birth
          value: 12/2/1970
        - name: Address
          value: 700 Avalon St <br> San Francisco, CA 94117
    - header: Household Details
      info-items:
        - name: Seniors in Household
          value: Yes
        - name: Veterans in Household
          value: Yes
        - name: People with Developmental Disabilities
          value: Yes