context:
  buckets:
   - name: Certificate of Preference
     units: up to 50 units
     applicants: 10 applicants on this list
     rank: "10"
     overall: Your ranking in this list is 10 out of of 10 qualified applicants.
   - name: Displaced Tenants Housing Preference
     units: up to 10 units
     applicants: 15 applicants on this list
     rank: "15"
     overall: Your ranking in this list is 15 out of of 15 qualified applicants.
   - name: Neighborhood Resident Housing Preference
     units: up to 20 units
     applicants: 1200 applicants on this list
     download: true
     rank: "285"
     overall: Your ranking in this list is 285 out of of 1200 qualified applicants.
   - name: Live/Work Preference
     units: any remaining units
     applicants: 2800 applicants on this list
     download: true
     rank: "385"
     overall: Your ranking in this list is 385 out of of 2800 qualified applicants.
  buckets-stats:
   - name: Certificate of Preference
     units: up to 50 units
     applicants: 10 applicants on this list
     rank: "10"
     overall: Your ranking in this list is 10 out of of 10 qualified applicants.
     has-stat: true
   - name: Displaced Tenants Housing Preference
     units: up to 10 units
     applicants: 15 applicants on this list
     rank: "15"
     overall: Your ranking in this list is 15 out of of 15 qualified applicants.
     has-stat: true
   - name: Neighborhood Resident Housing Preference
     units: up to 20 units
     applicants: 1200 applicants on this list
     download: true
     rank: "285"
     overall: Your ranking in this list is 285 out of of 1200 qualified applicants.
     has-stat: true
   - name: Live/Work Preference
     units: any remaining units
     applicants: 2800 applicants on this list
     download: true
     rank: "385"
     overall: Your ranking in this list is 385 out of of 2800 qualified applicants.
     has-stat: true