notes: |
  We recommend a font system that uses two open-source font families: Open Sans Pro and Droid Serif, both of which are designed for legibility and can beautifully adapt to a variety of visual styles.