context:
  results:
    - rank: "1"
      ticket: "671086"
    - rank: "2"
      ticket: "671030"
    - rank: "3"
      ticket: "671027"
    - rank: "4"
      ticket: "671037"
    - rank: "5"
      ticket: "671023"
    - rank: "6"
      ticket: "671057"
    - rank: "7"
      ticket: "671100"
    - rank: "8"
      ticket: "671036"
    - rank: "9"
      ticket: "671071"
    - rank: "10"
      ticket: "671059"
    - rank: "11"
      ticket: "671050"
    - rank: "12"
      ticket: "671039"
    - rank: "13"
      ticket: "671066"
    - rank: "14"
      ticket: "671045"
    - rank: "15"
      ticket: "671103"
    - rank: "16"
      ticket: "671031"
    - rank: "17"
      ticket: "671097"
    - rank: "18"
      ticket: "671060"
    - rank: "19"
      ticket: "671072"
    - rank: "20"
      ticket: "671065"