context:
  locations:
    - name: "Asian, Inc."
      languages: 
        - Cantonese
        - Vietnamese
      address: "167 Mission Street, 4th Floor"
      citystate: "San Francisco, CA 94103"
      phone: "415-928-5910"
      website: "asianinc.org"
    - name: "Bill Sorro Housing Program of the Veterans Equity Center"
      languages: 
        - Tagalog
      address: "1010 Mission Street, Suite C"
      citystate: "San Francisco, CA 94103"
      phone: "415-255-2347"
      website: "bishop.vetsequitycenter.org"
    - name: "Consumer Credit Counseling Service of San Francisco"
      languages: ""
      address: "595 Market Street, 15th Floor"
      citystate: "San Francisco, CA 94105"
      phone: "800-777-7526"
      website: "cccssf.org"
    - name: "Mission Economic Development Agency"
      languages: 
        - Spanish
      address: "2301 Mission Street, Suite 301"
      citystate: "San Francisco, CA 94103"
      phone: "415-282-3334"
      website: "medasf.org"
    - name: "San Francisco Housing Development Corporation"
      languages: ""
      address: "4439 Third Street"
      citystate: "San Francisco, CA 94124"
      phone: "415-822-1022"
      website: "asfhdc.org"
    - name: "San Francisco LGBT Center"
      languages: ""
      address: "1800 Market Street"
      citystate: "San Francisco, CA 94102"
      phone: "415-865-5661"
      website: "sfcenter.org"

  chinese:
    - name: "Asian, Inc."
      languages: 
        - Cantonese
        - Vietnamese
      address: "167 Mission Street, 4th Floor"
      citystate: "San Francisco, CA 94103"
      phone: "415-928-5910"
      website: "asianinc.org"

  espanol:
    - name: "Mission Economic Development Agency"
      languages: 
        - Spanish
      address: "2301 Mission Street, Suite 301"
      citystate: "San Francisco, CA 94103"
      phone: "415-282-3334"
      website: "medasf.org"
  rentals: 
    - name: City of SF Affordable Rental Units
      url: http://sfmohcd.org/affordable-housing-developments-san-francisco
      description: Family Housing
      location: San Francisco
    - name: City of SF Middle-Income Rental Units
      url: http://sfmohcd.org/middle-income-rental-housing-program
      description: Individual and Family Housing
      location: San Francisco Bay Area
    - name: Episcopal Community Services
      url: http://sfmohcd.org/sites/default/files/Documents/MOH/ECS%20Listings.pdf
      description: Individual and Family Housing
      location: San Francisco Bay Area
    - name: Compass One Home
      url: https://www.onehomebayarea.org
      description: Individual and Family Housing
      location: San Francisco Bay Area

  ownership: 
    - name: Below Market Rate Ownership Units
      url: http://sfmohcd.org/current-listings-below-market-rate-ownership-units
      location: San Francisco