context:
  applicants:
    - preference: COP 1
      application: APP-111-2223
      first: Anne
      last: Bowler
      phone: 646-248-1112
      address: 4106 Terrace St
      update: none
      status: Status
      row_status: 
      button_status: tertiary
    - preference: COP 2
      application: APP-111-2223
      first: Beth
      last: Bowler
      phone: 646-248-1112
      address: 4106 Terrace St
      update: none
      status: Processing
      row_status: is-processing
      button_status: is-processing
    - preference: COP 3
      application: APP-111-2223
      first: Beth
      last: Bowler
      phone: 646-248-1112
      address: 4106 Terrace St
      update: none
      status: Disqualified
      row_status: is-disqualified
      button_status: is-disqualified
    - preference: COP 4
      application: APP-111-2223
      first: Beth
      last: Bowler
      phone: 646-248-1112
      address: 4106 Terrace St
      update: none
      status: Approved
      row_status: is-approved
      button_status: is-approved
    - preference: COP 5
      application: APP-111-2223
      first: Beth
      last: Bowler
      phone: 646-248-1112
      address: 4106 Terrace St
      update: none
      status: Waitlisted
      row_status: is-waitlisted
      button_status: is-waitlisted
    - preference: COP 6
      application: APP-111-2223
      first: Beth
      last: Bowler
      phone: 646-248-1112
      address: 4106 Terrace St
      update: none
      status: Appealed
      row_status: is-appealed
      button_status: is-appealed
    - preference: COP 7
      application: APP-111-2223
      first: Beth
      last: Bowler
      phone: 646-248-1112
      address: 4106 Terrace St
      update: none
      status: Withdrawn
      row_status: is-withdrawn
      button_status: is-withdrawn
    - preference: COP 8
      application: APP-111-2223
      first: Beth
      last: Bowler
      phone: 646-248-1112
      address: 4106 Terrace St
      update: none
      status: Lease Signed
      invalid_status: is-invalid
      row_status: is-leased
      button_status: is-leased
    - preference: COP 9
      application: APP-111-2223
      first: Anne
      last: Bowler
      phone: 646-248-1112
      address: 4106 Terrace St
      update: none
      status: Processing
      invalid_status: is-invalid
      row_status: is-processing
      button_status: is-processing