context:
  inputs:
    states:
      - name: Alabama
        attr: AL
      - name: Alaska
        attr: AK
      - name: Arizona
        attr: AK
      - name: Arkansas
        attr: AK
      - name: California
        attr: CA
      - name: Colorado
        attr: CO
      - name: Connecticut
        attr: CT
      - name: Delaware
        attr: DE
      - name: District Of Columbia
        attr: DC
      - name: Florida
        attr: FL
      - name: Georgia
        attr: GA
      - name: Hawaii
        attr: HI
      - name: Idaho
        attr: ID
      - name: Illinois
        attr: IL
      - name: Indiana
        attr: IN
      - name: Iowa
        attr: IA
      - name: Kansas
        attr: KS
      - name: Kentucky
        attr: KY
      - name: Louisiana
        attr: LA
      - name: Maine
        attr: ME
      - name: Maryland
        attr: MD
      - name: Massachusetts
        attr: MA
      - name: Michigan
        attr: MI
      - name: Minnesota
        attr: MN
      - name: Mississippi
        attr: MS
      - name: Missouri
        attr: MO
      - name: Montana
        attr: MT
      - name: Nebraska
        attr: NE
      - name: Nevada
        attr: NV
      - name: New Hampshire
        attr: NH
      - name: New Jersey
        attr: NJ
      - name: New Mexico
        attr: NM
      - name: New York
        attr: NY
      - name: North Carolina
        attr: NC
      - name: North Dakota
        attr: ND
      - name: Ohio
        attr: OH
      - name: Oklahoma
        attr: OK
      - name: Oregon
        attr: OR
      - name: Pennsylvania
        attr: PA
      - name: Rhode Island
        attr: RI
      - name: South Carolina
        attr: SC
      - name: South Dakota
        attr: SD
      - name: Tennessee
        attr: TN
      - name: Texas
        attr: TX
      - name: Utah
        attr: UT
      - name: Vermont
        attr: VT
      - name: Virginia
        attr: VA
      - name: Washington
        attr: WA
      - name: West Virginia
        attr: WV
      - name: Wisconsin
        attr: WI
      - name: Wyoming
        attr: WY